import "./globals.css";


import { Roboto_Mono } from 'next/font/google'
 

const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  weight: "400",
  display: 'swap',
})

export const metadata = {
  title: "Clerk weather app",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto_mono.className}>
      <body>
          <div className="flex flex-col bg-blue-200 w-full min-h-screen h-[40rem] text-black text-center items-center justify-center">
            {children}
          </div>
      </body>
    </html>
  );
}

export default RootLayout;
